version: "3.8"

services:
  airbnb-db:
    image: postgres
    container_name: airbnb-db
    environment:
      - POSTGRES_DB=airbnbDB
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - airbnb-network
    volumes:
      - airbnb-db-data:/var/lib/postgresql/data

  airbnb_app:
    image: anuj55149/airbnb_app
    container_name: airbnb_app
    networks:
      - airbnb-network
    depends_on:
      - airbnb-db
    ports:
      - "8080:8080"

volumes:
  airbnb-db-data:

networks:
  airbnb-network: